DarkBruce/sprint2021-team-2-repo

.gitignore, dinesafelysite/settings.py
- Remove .DS_Store from the git history
- Add `DEBUG` environment, it is better for developer to work locally
=> Add debug environment

user/tests.py
Added additional testing to cover request.POST with user profile information
=> Register user w profile

user/tests.py
=> add more test

user/tests.py, user/views.py
Fix profile pic disappear problem
=> Fix profile pic disappear problem

restaurant/templates/restaurant_detail.html
- Implement rating view
- profile page
=> Implement rating view

restaurant/forms.py, restaurant/templates/restaurant_detail.html, restaurant/tests.py, restaurant/views.py, user/forms.py
Created initial functionality for creating reviews including the frontend and backend components. Still need some testing and validation for edge cases.
=> User reviews

restaurant/templates/restaurant_detail.html, restaurant/urls.py, restaurant/views.py
=> Implement edit and delete rating comments

restaurant/tests.py, user/admin.py, user/models.py
This PR add comment & review_tickets (for both review and comment) models in user/models.py
=> add comment & review_tickets models

restaurant/tests.py, restaurant/urls.py, restaurant/views.py
- Add the delete comment views function in restaurant/views.py
- Add corresponding url in restaurant/urls.py
- Add corresponding tests in restaurant/test.py
=> Add Delete Comment Function

restaurant/templates/restaurant_detail.html, restaurant/tests.py, restaurant/urls.py, restaurant/views.py
- Implement edit comment
```js
this.renderReplies({
profile: 'https://s3.aws.com/profile/img/abcde',
text: 'this is a reply', 
author: 'userId',
commentId: 'commentId'
})
```
```js
internalReviews.forEach(review => {
const reviewWrapper = document.getElementById('internal_review');
const ratingReview = document.createElement('rating-review');
ratingReview.setAttribute('profile-img', review.user__user_profile__photo);
ratingReview.setAttribute('profile-img-alt', review.user__username);
ratingReview.setAttribute('user-name', review.user__username);
ratingReview.setAttribute('time-created', review.time);
ratingReview.setAttribute('user-rating', review.rating);
ratingReview.setAttribute('review-text', review.content);
ratingReview.setAttribute('review-id', review.id); …
```
=> Implement edit comment

restaurant/templates/restaurant_detail.html, restaurant/views.py
* Update restaurant_html and views to display user comments on frontend
* use DEFUALT_AVATAR for profile picture
=> updated restaurant_detail and views to display user comments

restaurant/templates/restaurant_detail.html, restaurant/tests.py, restaurant/urls.py, restaurant/views.py, user/forms.py
**For reporting functionalities:**
- Add forms in user/forms.py
- Add view functions in restaurant/views.py
- Add urls in restaurant/urls.py
- Add tests to make sure the report ticket models are working
- Add tests to make sure the report views & forms are working
**For frontend to use:**
- specified the post urls as instructed in restaurant/urls.py
- form content should at least contain one text field with ID "reason"
=> add report functions

restaurant/templates/restaurant_detail.html, restaurant/views.py, user/signals.py, user/templates/login.html, user/templates/profile.html, user/views.py
* 3rd party login with checks for duplicate email or user account
* redirect to login and show temp message if duplicate account
* display review comments
=> Comments view

restaurant/tests.py
=> add create comment test

restaurant/templates/restaurant_detail.html, user/templates/facing_page.html, user/tests.py, user/urls.py, user/views.py
Add a facing-page for the user. 
Add tests for facing-page
=> Facing page

user/models.py
add hidden field into reviews & comments model in user/models.py
=> add hidden field to reviews & comments model

restaurant/templates/restaurant_detail.html
- Implement the hidden post
- When `hidden` flag is on:
- For post author: show hints
- For others: hide the post
- Otherwise, show as usual
=> Implement FE hidden post

user/templates/facing_page.html
Add additional CSS to make public profile page look better
=> update facing__page.html with additional styling

user/templates/facing_page.html
Remove Comments form facing_page.html
=> Public page style

dinesafelysite/urls.py, restaurant/templates/restaurant_detail.html, restaurant/views.py, user/forms.py
- Add posting picture functions in restaurant/views.py
- Modify the UserQuestionaireForm in user/forms.py to allow adding pictures
- Add media_url to return context parameters in **get_restaurant_profile** in restaurant/views.py
=> Add posting pictures function for reviews

restaurant/templates/restaurant_detail.html, restaurant/views.py
PR includes changes to restaurant_detail.html to create attributes and display the images uploaded by user in review. Also includes styling for the images.
=> Display review images

restaurant/utils.py, restaurant/views.py
- add `send_moderate_notification_email` to restaurant/utils.py
- add sending notification lines to report/hide/delete views function on reported review/comment
=> add email notification for report/hide/delete reported review/comment event 

restaurant/templates/restaurant_detail.html
- add like button
- suggestion:
- return number of current likes
- return if the user is like or not, if like, display blue, otherwise, gray
=> add like button

frontend/src/App.jsx, restaurant/templates/restaurant_detail.html
- Move `react` script to aws s3
=> add aws s3 cdn

frontend/src/YelpReview/CommentBox.js, frontend/src/YelpReview/YelpReview.css, frontend/src/YelpReview/YelpReview.js
- Adjust styles 
- Fix report comments
=> Fix report comments issue

frontend/src/YelpReview/YelpReview.css, frontend/src/YelpReview/YelpReview.js
- Implement load more comment button
=> Implement load more comment button

frontend/src/App.jsx, frontend/src/YelpReview/CommentBox.js, frontend/src/YelpReview/Popover.js, frontend/src/YelpReview/YelpReview.js, frontend/src/components/OpeningHours/OpeningHours.js, frontend/src/index.jsx, restaurant/templates/restaurant_detail.html
- Disabled submit button
- Add popup
=> Disabled submit button after click and add popup
